apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-site-ingress
  namespace: personal
  # for prod - 
  # annotations:
  #   cert-manager.io/cluster-issuer: "letsencrypt-prod"
  #   nginx.ingress.kubernetes.io/ssl-redirect: "true"

# Ingress isn't really necessary since we'l use cloudflare for public access
 
spec:
  ingressClassName: nginx
  # for prod
  # tls:
  #   - hosts:
  #       - personal.example.com
  #     secretName: personal-site-tls
  rules:
    # - host: personal.example.com   # the hostname Cloudflare will send traffic for
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: personal_site_prod
              port:
                number: 8000